module.exports = {
  siteTitle: 'mPro',
  siteTitleAlt: 'mpro blog',
  publisher: 'William Winberg',
  siteDescription:
    'A static blog website for mpro made with Gatsby, Contentful and Netlify',
  siteUrl: 'https://mpro.netlify.com',
  postsPerHomePage: 7,
  postsPerPage: 6,
  author: 'William Winberg',
  authorUrl: 'https://williamwinberg.com',
  userTwitter: '@harm13ss',
  shortTitle: 'News App',
  shareImage: '/logos/share.jpg',
  shareImageWidth: 900,
  shareImageHeight: 600,
  siteLogo: '/logos/logo.png',
  backgroundColor: '#e9e9e9',
  themeColor: '#121212',
  copyright: 'Copyright © 2018 William Winberg',
}
